---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heycar-app
spec:
  selector:
    matchLabels:
      app: heycar-app
  replicas: 2
  template:
    metadata:
      labels:
        app: heycar-app
    spec:
      containers:
        - name:  heycar-app
          image: #Image Registry URL
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: heycar-app
spec:
  selector:
    app: heycar-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: heycar-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: heycar-app
              servicePort: 80